[package]
name = "video-encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ratatui = "0.24"
crossterm = "0.27"
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"
ffmpeg-next = "7.0"

[dev-dependencies]
tempfile = "3.8"